fix: change wrong code

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -178,7 +178,7 @@ jobs:
       #   with:
       #     node-version: "20"
 
-      - name: Install dependencies of Back
+      - name: Install Dependencies of Back
         working-directory: ./server
         run: npm i
 
@@ -192,16 +192,16 @@ jobs:
             rm -rf /var/www/backend
             mkdir /var/www/backend'
           rsync -avz -e "ssh" ./server/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend
-          rsync -avz -e "ssh" ./server/package.json/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend/package.json
-            ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}  '
-          export NVM_DIR="$HOME/.nvm"
-          if [ -s "$NVM_DIR/nvm.sh" ]; then
-            . "$NVM_DIR/nvm.sh"
-          else
-            echo "nvm.sh not found"
-            exit 1
-          fi
+          rsync -avz -e "ssh" ./server/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend/package.json
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}  '
+            export NVM_DIR="$HOME/.nvm"
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+            else
+              echo "nvm.sh not found"
+              exit 1
+            fi
 
-          nvm use --lts
-          cd /var/www/backend
-          npm i --production'
+            nvm use --lts
+            cd /var/www/backend
+            npm i --production'
